import { useState } from 'react'

const jobs = [['#VID-2048', 'High', '25s ago', '72%', '2 / 3', 'video-q'], ['#IMG-3912', 'Normal', '5m ago', '45%', '2 / 5', 'image-q'], ['#RPT-1840', 'High', '8m ago', '91%', '3 / 3', 'report-q'], ['#CSV-7721', 'Normal', '11m ago', '31%', '—', 'csv-q']]
const nav = ['Overview', 'Jobs', 'Workers', 'Schedules', 'Dead letter', 'Metrics']

function App() {
  const [active, setActive] = useState('Overview')
  const [notice, setNotice] = useState(false)
  return <div className="min-h-screen bg-[#f8f8f7] text-[#121313]">
    <aside className="fixed inset-y-0 hidden w-60 border-r border-black/10 bg-white px-5 py-7 lg:flex lg:flex-col">
      <div className="text-2xl font-semibold tracking-[-0.08em]"><span className="mr-2 text-lime-500">●—●</span>Queue<span className="font-normal">Flow</span></div>
      <nav className="mt-12 space-y-2">{nav.map((item) => <button key={item} onClick={() => setActive(item)} className={`block w-full rounded-lg px-4 py-3 text-left text-sm ${active === item ? 'bg-[#111617] text-white' : 'text-slate-700 hover:bg-slate-100'}`}>{item}</button>)}</nav>
      <div className="mt-auto rounded-xl border border-black/10 p-4 text-xs"><p className="text-slate-500"><i className="mr-2 inline-block h-2 w-2 rounded-full bg-lime-500" />System health</p><b className="mt-2 block text-lg">Preview</b><p className="mt-1 leading-5 text-slate-500">Live health appears when workers connect.</p></div>
    </aside>
    <main className="lg:ml-60"><header className="flex h-24 items-center gap-4 border-b border-black/10 bg-white px-6 lg:px-8"><button className="rounded-xl border border-black/10 px-4 py-3 text-sm"><i className="mr-2 inline-block h-2 w-2 rounded-full bg-lime-500" />Development⌄</button><label className="mx-auto hidden max-w-[30rem] flex-1 rounded-xl border border-black/10 px-4 py-3 text-sm text-slate-400 md:block">⌕　Search jobs, queues, workers…</label><button aria-label="Notifications" className="text-xl">♧<sup className="rounded-full bg-black px-1.5 py-0.5 text-[10px] text-white">3</sup></button><button onClick={() => setNotice(true)} className="rounded-xl bg-[#0d1213] px-5 py-3 text-sm font-medium text-white">＋ New job</button></header>
      <section className="mx-auto max-w-[1280px] px-6 py-8 lg:px-7"><div className="flex items-center gap-4"><h1 className="text-4xl font-medium tracking-[-0.05em]">{active === 'Overview' ? 'Queue operations' : active}</h1><span className="text-sm"><i className="mr-2 inline-block h-2 w-2 rounded-full bg-lime-500" />Preview</span></div><p className="mt-2 text-sm text-slate-500">Interface preview — real queue data will connect to the API in the final dashboard milestone.</p>
        <div className="mt-7 grid gap-3 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Throughput" value="124" unit="/ min" note="Jobs per minute" dark/><Metric label="Queued" value="38" note="Jobs waiting"/><Metric label="Active" value="12" note="Jobs in progress"/><Metric label="Success" value="98.7" unit="%" note="Success rate"/></div><QueueTable/><div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><Chart/><Controls/></div></div><div className="space-y-4"><Workers/><Events/></div></div>
      </section></main>{notice && <div role="dialog" className="fixed inset-0 grid place-items-center bg-black/30 p-5"><div className="max-w-sm rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-medium">New job</h2><p className="mt-2 text-sm leading-6 text-slate-500">Job creation will be connected once the API domain is ready.</p><button onClick={() => setNotice(false)} className="mt-5 rounded-lg bg-black px-4 py-2 text-sm text-white">Close</button></div></div>}</div>
}
function Metric({label,value,unit,note,dark=false}:{label:string;value:string;unit?:string;note:string;dark?:boolean}) { return <article className={`rounded-2xl border p-5 ${dark?'border-[#111617] bg-[#111617] text-white':'border-black/10 bg-white'}`}><p className="text-sm">{label}</p><p className="mt-4 text-4xl tracking-[-.06em]">{value}<small className="ml-1 text-lg">{unit}</small></p><p className={`mt-3 text-xs ${dark?'text-slate-300':'text-slate-500'}`}>{note}</p></article> }
function QueueTable(){ return <section className="overflow-hidden rounded-2xl border border-black/10 bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-medium">Live queue</h2><button className="rounded-lg border border-black/15 px-3 py-2 text-xs">All queues⌄</button></div><div className="mt-5 flex gap-6 border-b border-black/10 text-sm"><b className="border-b-4 border-lime-500 pb-3">Queued <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-normal">38</span></b><span>Running　12</span><span>Retrying　6</span></div><div className="overflow-x-auto"><table className="mt-2 w-full min-w-[650px] text-left text-xs"><thead className="text-slate-400"><tr><th>Job ID</th><th>Priority</th><th>Added</th><th>Progress</th><th>Attempts</th><th>Queue</th></tr></thead><tbody>{jobs.map(([id,priority,added,progress,attempts,queue])=><tr key={id} className="border-t border-black/8"><td className="py-4 text-sm font-medium">{id}</td><td><span className={`rounded px-2 py-1 ${priority==='High'?'bg-red-50 text-red-500':'bg-slate-100 text-slate-500'}`}>{priority}</span></td><td className="text-slate-500">{added}</td><td><div className="flex gap-2"><i className="h-1.5 w-20 overflow-hidden rounded bg-slate-200"><i className="block h-full bg-lime-500" style={{width:progress}}/></i>{progress}</div></td><td>{attempts}</td><td className="text-slate-500">{queue}</td></tr>)}</tbody></table></div></section> }
function Workers(){return <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-medium">Worker status</h2><div className="mt-5 border-t border-black/10">{[['worker-01','Online','68%'],['worker-02','Online','42%'],['worker-03','Offline','0%']].map(([name,status,cpu])=><div key={name} className="flex items-center justify-between border-b border-black/10 py-4 text-sm"><span><i className={`mr-2 inline-block h-2 w-2 rounded-full ${status==='Online'?'bg-lime-500':'bg-red-400'}`}/>{name}<small className="ml-3 text-slate-400">{status}</small></span><b className={`rounded px-3 py-2 text-xs font-normal ${status==='Online'?'bg-lime-100':'bg-red-50'}`}>{cpu}</b></div>)}</div></section>}
function Events(){return <section className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-medium">Event feed</h2><button className="text-sm">View all →</button></div>{['Job completed','Retry scheduled','Worker disconnected','Moved to dead letter'].map((event,index)=><div key={event} className="flex items-center gap-3 border-b border-black/10 py-5 text-sm last:border-0"><i className={`grid h-6 w-6 place-items-center rounded-full border ${index===2?'border-red-400 text-red-500':'border-lime-500 text-lime-600'}`}>{index===2?'!':'✓'}</i>{event}<time className="ml-auto text-xs text-slate-400">10:59</time></div>)}</section>}
function Chart(){return <section className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-medium">Throughput & latency</h2><b className="rounded bg-black px-2 py-1 text-xs font-normal text-white">1H</b></div><div className="mt-6 flex h-32 items-end gap-3 border-b border-l border-black/10 px-3">{[35,58,45,70,88,62,75,54,68,42].map((height,index)=><i key={index} className="w-full rounded-t bg-violet-200" style={{height:`${height}%`}}/>)}</div><p className="mt-3 text-xs text-slate-400">Preview — metrics will be loaded from Prometheus.</p></section>}
function Controls(){return <section className="rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-lg font-medium">Test controls</h2><p className="mt-3 text-sm leading-6 text-slate-500">Failure simulation activates once workers and recovery rules are connected.</p><div className="mt-5 grid grid-cols-3 gap-2"><button className="rounded-lg border border-black/15 py-3 text-sm">Worker</button><button className="rounded-lg border border-black/15 py-3 text-sm">Queue</button><button className="rounded-lg border border-black/15 py-3 text-sm">Network</button></div><button disabled className="mt-4 w-full rounded-lg bg-slate-200 py-3 text-sm text-slate-500">Simulate failure</button></section>}
export default App
